apiVersion: v1
kind: PersistentVolume
metadata:
  name: rag-stores
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: genetics-rag-20260309
    fsType: ext4
  storageClassName: ""
  claimRef:
    namespace: genetics
    name: rag-stores
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-stores
  namespace: genetics
spec:
  storageClassName: ""
  volumeName: rag-stores
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
