apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-data
  namespace: genetics
spec:
  storageClassName: standard-rwo
  accessModes:
    - ReadWriteOnce
  volumeName: chat-data-restored-pv
  resources:
    requests:
      storage: 10Gi
